RetroReview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('review.urls'), name='review_urls'),
    path('accounts/', include('allauth.urls')),
]

review/urls.py
from . import views
from django.urls import path, include


urlpatterns = [
    path('', views.GameList.as_view(), name='home'),
#    path('<slug:slug>/', views.ReviewDetail.as_view(), name='review_detail'), #Slug converter!
#    path('<slug:slug>/', views.GameReviews.as_view(), name='reviews'), # TO BE EDITED!
    #path('reviews/<slug:slug>/', views.ReviewDetail.as_view(), name='reviews'),
    path('<slug:slug>/', views.GameDetail.as_view(), name='game_detail'),
    path('<slug:game>/<slug:review>/', views.ReviewDetail.as_view(), name='review_detail'),
]                              

review/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from .stars import STARS
from .genres import GENRES
from .status import STATUS
from .years import YEARS
from .platforms import PLATFORMS

# Create your models here.


class Game(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    genre = models.CharField(max_length=100, choices=GENRES, blank=True)
    year = models.IntegerField(choices=YEARS, blank=True)
    platform = models.CharField(max_length=100, choices=PLATFORMS, blank=True)
    featured_image = CloudinaryField('image', default='placeholder')
    rating = models.DecimalField(max_digits=2, decimal_places=1) # ForeignKey? l#inherit from class Review? # generated by overall reviews
    description = models.TextField()

    class Meta:
        ordering = ['-rating'] # or order by -created_on?

    def __str__(self):
        return self.title
    

class Review(models.Model):
    title = models.CharField(max_length=200, unique=True, blank=True) # default=Game.title? # can act as excerpt?
    slug = models.SlugField(max_length=200, unique=True, default='')
    username = models.ForeignKey(User, on_delete=models.CASCADE) #ForeignKey?
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    #review_image = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='review_image') #CloudinaryField('image', default='placeholder') # Users can upload their own screenshots?
    excerpt = models.TextField(blank=True)
    status = models.IntegerField(choices=STATUS, default=0) 
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    rating = models.DecimalField(choices=STARS, max_digits=2, decimal_places=1) # ForeignKey?
    id = models.AutoField(primary_key=True, editable=False)    
    
    #class Meta:
    #    ordering = ['-likes'] # fails at migration

    def number_of_likes(self):
        return self.likes.count()
    
    def ordered_by_likes(self):
        return self.likes.order_by('-likes')

    def __str__(self):
        return f"Review {self.content} by {self.username}"


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')
    username = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.username}"

review/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from .models import Game, Review, Comment

# Create your views here.

class GameList(generic.ListView):
    model = Game
    queryset = Game.objects.all()   # .order_by('-rating')
    template_name = 'index.html'
    paginate_by = 6


class GameReviews(generic.ListView):    # Site, where all Reviews are listed
    model = Review
    #slug = Game.slug                      # --> TO BE EDITED!
    queryset = Review.objects.all()        #(slug=slug)      # filter() #all() # Review.objects.filter(slug=game.title)
    template_name = 'reviews.html'       #for every game there is a different slug (URL)
    paginate_by = 6



class GameDetail(View):   #Früher: ReviewDetail
    
    def get(self, request, slug, *args, **kwargs):
        #review = Review,
        queryset = Review.objects.filter(status=1)     #  
        game = get_object_or_404(Game, slug=slug)
        reviews = game.review_set.filter(status=1).order_by('-created_on') # Get all reviews related to the game
        #comments = review.comments.filter(approved=True).order_by('created_on') # in walktrough: comments.filter(approved=True).order_by
        liked = False
        if request.user.is_authenticated:
            if reviews.filter(likes=request.user).exists():
                liked = True
        #if review.likes.filter(id=self.request.user.id).exists():
        #    liked = True

        return render(
            request,
            "game_detail.html",
            {   
                "game": game,
                "reviews": reviews,     # Pass the reviews related to the game to the context
                #"comments": comments,
                #"commented": True,
                "liked": liked,

                #"comment_form": CommentForm(),
            },
        )
    
class ReviewDetail(View):
    def get(self, request, game, review, *args, **kwargs):
        queryset = Review.objects.filter(status=1)
        game = get_object_or_404(Game, slug=game)
        review = get_object_or_404(queryset, slug=review)
        #reviews = game.review_set.filter(status=1).order_by('-created_on') # Get all reviews related to the game
        comments = review.comments.filter(approved=True).order_by('created_on') # in walktrough: comments.filter(approved=True).order_by
        liked = False
        if review.likes.filter(id=self.request.user.id).exists():
            liked = True
        #if review.likes.filter(id=self.request.user.id).exists():
        #    liked = True

        return render(
            request,
            "review_detail.html",
            {
                "review": review,
                "comments": comments,
                "liked": liked,
                "game": game,
            }
        )

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>CodeStar Blog</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">R</span><span>etro</span><span class="brand">R</span><span>eview</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    adventures of a software developer
                </span>
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 main-bg"> <!-- main class="col-md-12 col-lg-12 min-vh-100 main-bg maincontent ) " -->
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Code Instituters</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>
</body>

</html>

templates/game_detail.html
{% extends 'base.html' %} {% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ game.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ game.genre }} | {{ game.year }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in game.featured_image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src=" {{ game.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <!-- Games Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
            {% for review in reviews %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h1> {{ review.title }}</h1>
                            <p class="card-text">
                                Author: {{ review.username }}
                            </p>
                            <p class="card-text">
                                Date: {{ review.created_on }}
                            </p>
                            <p class="card-text">
                                {{ review.content | safe}}
                            </p>  
                        </div>
                    </div>
                </div>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
        </div>
</div>
    
    

<!-- Reviews -->
<div class="container-fluid">
    <div class="row">


        <div class="col-12 mt-3 left">
            <div class="row">
            {% for review in reviews %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in game.featured_image.url %}
                                <img class="card-img-top" 
                                    src="https://thenounproject.com/api/private/icons/3674270/edit/?backgroundShape=SQUARE&backgroundShapeColor=%23000000&backgroundShapeOpacity=0&exportSize=752&flipX=false&flipY=false&foregroundColor=%23000000&foregroundOpacity=1&imageFormat=png&rotation=0" alt="No image available">
                                {% else %}
                                <img class="card-img-top" src="{{ game.featured_image.url }}" alt="Game cover image">
                                {% endif %}
                            </div>
                            <div>
                                <a href="{% url 'review_detail' game.slug review.slug %}" class="post-link">   <!-- add game.id? -->
                                    <h2 class ="card-title">{{ review.title }}</h2>
                                </a>
                            </div>
                            <div class="col-3">
                                <!-- The number of likes goes before the closing strong tag -->
                                <strong class="text-secondary"><i class="far fa-thumbs-up" style="color: red"></i> {{ review.number_of_likes }} </strong>
                                <strong class="text-secondary"><i class="far fa-star style" style="color: goldenrod"></i>{{ review.rating }}</strong>
                            </div>
                            <br>
                            <br>
                            <div class="image-flash">                   
                                <p class="author">Review by: {{ review.username }}</p>  <!-- class from walktrough, see style.css -->
                            </div>
                               <!-- <p class="card-text">{{ review.content }}</p> --> <!-- to be edited! -->
                               
                                
                            
                            <!--  <i class="far fa-star"></i>{{ game.rating }} --> <!-- to be edited! --> 
                            
                        </div>
                    </div>
                </div>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>




<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ review.content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <!-- The number of likes goes before the closing strong tag -->
                        <strong class="text-secondary"><i class="far fa-heart"></i> {{ review.number_of_likes }} </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.username }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Games Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
            {% for game in game_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container card-img-top">
                                {% if "placeholder" in game.featured_image.url %}
                                <img class="card-img-top" 
                                    src="https://thenounproject.com/api/private/icons/3674270/edit/?backgroundShape=SQUARE&backgroundShapeColor=%23000000&backgroundShapeOpacity=0&exportSize=752&flipX=false&flipY=false&foregroundColor=%23000000&foregroundOpacity=1&imageFormat=png&rotation=0" alt="No image available">
                                {% else %}
                                <img class="card-img-top" src="{{ game.featured_image.url }}" alt="Game cover image">
                                {% endif %}
                            </div>  
                            <div class="image-flash">                   
                            <!--    <p class="author">{{ game.title }}</p> -->  <!-- class from walktrough, see style.css -->
                            </div>
                            <div>
                                <a href="{% url 'game_detail' game.slug %}" class="post-link">   <!-- add game.id? -->
                                    <h2 class ="card-title">{{ game.title }}</h2>
                                    <p class="card-text">{{ game.genre }}</p> 
                                    <p class="card-text">{{ game.developer }}</p> <!-- to be edited! -->
                                    <p class="card-text text-muted h6">{{ game.year }}</p>
                                </a>
                            <!--  <i class="far fa-star"></i>{{ game.rating }} --> <!-- to be edited! --> 
                            </div> 
                            <hr />
                        </div>
                    </div>
                </div>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">
                </h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle"> | </p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src="" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text "></p>
                <div class="row">

                    <div class="col-1">
                        <!-- The number of likes goes before the closing strong tag -->
                        <strong class="text-secondary"><i class="far fa-heart"></i> </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                        </strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the tags to iterate through each comment in comments -->
                {% %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{  | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/review_detail.html
{% extends 'base.html' %} {% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ review.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">Review by: {{ review.username }} | {{ review.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in game.featured_image.url %}
                <img src="https://thenounproject.com/api/private/icons/3674270/edit/?backgroundShape=SQUARE&backgroundShapeColor=%23000000&backgroundShapeOpacity=0&exportSize=752&flipX=false&flipY=false&foregroundColor=%23000000&foregroundOpacity=1&imageFormat=png&rotation=0" width="100%">
                {% else %}
                <img src=" {{ game.featured_image.url }}" alt="Game cover image" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text "> {{ review.content | safe }}</p>
                <div class="row">

                    <div class="col-1">
                        <!-- The number of likes goes before the closing strong tag -->
                        <strong class="text-secondary"><i class="far fa-heart"></i> {{ review.number_of_likes }} </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}
                        </strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.username }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/reviews.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Games Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
            {% for game in game_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in game.featured_image.url %}
                                <img class="card-img-top" 
                                    src="https://thenounproject.com/api/private/icons/3674270/edit/?backgroundShape=SQUARE&backgroundShapeColor=%23000000&backgroundShapeOpacity=0&exportSize=752&flipX=false&flipY=false&foregroundColor=%23000000&foregroundOpacity=1&imageFormat=png&rotation=0" alt="No image available" style="max-width: 350px; max-height: 250px">
                                {% else %}
                                <img class="card-img-top" src="{{ game.featured_image.url }}" alt="Game cover image" style="max-width: 350px; max-height: 250px">
                                {% endif %}
                                <div class="image-flash">                   
                                <!--    <p class="author">{{ game.title }}</p> -->  <!-- class from walktrough, see style.css -->
                                </div>
                                <a href="{% url 'reviews.detail' game.slug %}" class="post-link">   <!-- add game.id? -->
                                    <h2 class ="card-title">{{ game.title }}</h2>
                                    <p class="card-text">{{ game.genre }}</p> <!-- to be edited! -->
                                </a>
                                <hr />
                                <p class="card-text text-muted h6">{{ game.year }}</p>
                            <!--  <i class="far fa-star"></i>{{ game.rating }} --> <!-- to be edited! --> 
                            </div>
                        </div>
                    </div>
                </div>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}